apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
namespace: frontend
resources:
  - ../../../base
  - namespace.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: frontend
    path: patch-env-from.yaml

configMapGenerator:
  - envs:
      - dev-env.yaml
    name: envs
