/*
 * Copyright Fraunhofer Institute for Material Flow and Logistics
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * For details on the licensing terms, see the LICENSE file.
 * SPDX-License-Identifier: Apache-2.0
 */

import { Offer } from '@prisma/client';
import { Decimal } from '@prisma/client/runtime/library';
import { OfferStatesEnum } from '../../../util/src';
import { ServiceProcessesSeed } from './service-process.seed';

export const OffersSeed: Offer[] = <Offer[]>[
  {
    id: 'of001',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(13),
    price: new Decimal(5),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[0].id,
  },
  {
    id: 'of002',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(14),
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[0].id,
  },
  {
    id: 'of003',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[0].id,
  },
  {
    id: 'of004',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(16),
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[0].id,
  },
  {
    id: 'of005',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: new Decimal(13),
    price: new Decimal(5),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[1].id,
  },
  {
    id: 'of006',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: new Decimal(14),
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[1].id,
  },
  {
    id: 'of007',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[1].id,
  },
  {
    id: 'of008',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: new Decimal(16),
    price: new Decimal(21),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[1].id,
  },
  {
    id: 'of009',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(17),
    price: new Decimal(10),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[2].id,
  },
  {
    id: 'of010',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(18),
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[2].id,
  },
  {
    id: 'of011',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(19),
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[2].id,
  },
  {
    id: 'of012',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(20),
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[2].id,
  },
  {
    id: 'of013',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: new Decimal(21),
    price: new Decimal(5),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[3].id,
  },
  {
    id: 'of014',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: new Decimal(22),
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[3].id,
  },
  {
    id: 'of015',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: new Decimal(23),
    price: new Decimal(20),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[3].id,
  },
  {
    id: 'of016',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: new Decimal(24),
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[3].id,
  },
  {
    id: 'of017',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(25),
    price: new Decimal(18),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[4].id,
  },
  {
    id: 'of018',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(26),
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[4].id,
  },
  {
    id: 'of019',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(27),
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[4].id,
  },
  {
    id: 'of020',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(28),
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[4].id,
  },
  {
    id: 'of021',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(5),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[5].id,
  },
  {
    id: 'of022',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(60),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[5].id,
  },
  {
    id: 'of023',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[5].id,
  },
  {
    id: 'of024',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[5].id,
  },
  {
    id: 'of025',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(10),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[6].id,
  },
  {
    id: 'of026',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[6].id,
  },
  {
    id: 'of027',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[6].id,
  },
  {
    id: 'of028',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[6].id,
  },
  {
    id: 'of029',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(20),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[7].id,
  },
  {
    id: 'of030',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[7].id,
  },
  {
    id: 'of031',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[7].id,
  },
  {
    id: 'of032',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[7].id,
  },
  {
    id: 'of033',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(30),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[8].id,
  },
  {
    id: 'of034',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[8].id,
  },
  {
    id: 'of035',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[8].id,
  },
  {
    id: 'of036',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[8].id,
  },
  {
    id: 'of037',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(5),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[9].id,
  },
  {
    id: 'of038',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[9].id,
  },
  {
    id: 'of039',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(28),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[9].id,
  },
  {
    id: 'of040',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[9].id,
  },
  {
    id: 'of041',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(12),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[10].id,
  },
  {
    id: 'of042',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[10].id,
  },
  {
    id: 'of043',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[10].id,
  },
  {
    id: 'of044',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[10].id,
  },
  {
    id: 'of045',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(3),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[11].id,
  },
  {
    id: 'of046',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[11].id,
  },
  {
    id: 'of047',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[11].id,
  },
  {
    id: 'of048',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[11].id,
  },
  {
    id: 'of049',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(3),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[12].id,
  },
  {
    id: 'of050',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[12].id,
  },
  {
    id: 'of051',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[12].id,
  },
  {
    id: 'of052',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[12].id,
  },
  {
    id: 'of053',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(5),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[13].id,
  },
  {
    id: 'of054',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: new Decimal(15),
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[13].id,
  },
  {
    id: 'of055',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[13].id,
  },
  {
    id: 'of056',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(40),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[13].id,
  },
  {
    id: 'of057',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(54),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[14].id,
  },
  {
    id: 'of058',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[14].id,
  },
  {
    id: 'of059',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[14].id,
  },
  {
    id: 'of060',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[14].id,
  },
  {
    id: 'of061',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(5),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[15].id,
  },
  {
    id: 'of062',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[15].id,
  },
  {
    id: 'of063',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(80),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[15].id,
  },
  {
    id: 'of064',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[15].id,
  },
  {
    id: 'of065',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(36),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[16].id,
  },
  {
    id: 'of066',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[16].id,
  },
  {
    id: 'of067',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[16].id,
  },
  {
    id: 'of068',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[16].id,
  },
  {
    id: 'of069',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(9),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[17].id,
  },
  {
    id: 'of070',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[17].id,
  },
  {
    id: 'of071',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[17].id,
  },
  {
    id: 'of072',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[17].id,
  },
  {
    id: 'of073',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(28),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[18].id,
  },
  {
    id: 'of074',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[18].id,
  },
  {
    id: 'of075',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[18].id,
  },
  {
    id: 'of076',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[18].id,
  },
  {
    id: 'of077',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(5),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[19].id,
  },
  {
    id: 'of078',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[19].id,
  },
  {
    id: 'of079',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[19].id,
  },
  {
    id: 'of080',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(48),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[19].id,
  },
  {
    id: 'of081',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(24),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[20].id,
  },
  {
    id: 'of082',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[20].id,
  },
  {
    id: 'of083',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[20].id,
  },
  {
    id: 'of084',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[20].id,
  },
  {
    id: 'of085',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(5),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[21].id,
  },
  {
    id: 'of086',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(1),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[21].id,
  },
  {
    id: 'of087',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[21].id,
  },
  {
    id: 'of088',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[21].id,
  },
  {
    id: 'of089',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(50),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[22].id,
  },
  {
    id: 'of090',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[22].id,
  },
  {
    id: 'of091',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[22].id,
  },
  {
    id: 'of092',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[22].id,
  },
  {
    id: 'of093',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(36),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[23].id,
  },
  {
    id: 'of094',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[23].id,
  },
  {
    id: 'of095',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[23].id,
  },
  {
    id: 'of096',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[23].id,
  },
  {
    id: 'of097',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(9),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[24].id,
  },
  {
    id: 'of098',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[24].id,
  },
  {
    id: 'of099',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[24].id,
  },
  {
    id: 'of100',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[24].id,
  },
  {
    id: 'of101',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(5),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[25].id,
  },
  {
    id: 'of102',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[25].id,
  },
  {
    id: 'of103',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(60),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[25].id,
  },
  {
    id: 'of104',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[25].id,
  },
  {
    id: 'of105',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(2),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[26].id,
  },
  {
    id: 'of106',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[26].id,
  },
  {
    id: 'of107',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[26].id,
  },
  {
    id: 'of108',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[26].id,
  },
  {
    id: 'of109',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(5),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[27].id,
  },
  {
    id: 'of110',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[27].id,
  },
  {
    id: 'of111',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(7),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[27].id,
  },
  {
    id: 'of112',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[27].id,
  },
  {
    id: 'of113',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(18),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[28].id,
  },
  {
    id: 'of114',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[28].id,
  },
  {
    id: 'of115',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[28].id,
  },
  {
    id: 'of116',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[28].id,
  },
  {
    id: 'of117',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(5),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[29].id,
  },
  {
    id: 'of118',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[29].id,
  },
  {
    id: 'of119',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[29].id,
  },
  {
    id: 'of120',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(40),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[29].id,
  },
  {
    id: 'of121',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(12),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[30].id,
  },
  {
    id: 'of122',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[30].id,
  },
  {
    id: 'of123',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[30].id,
  },
  {
    id: 'of124',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[30].id,
  },
  {
    id: 'of125',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(5),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[31].id,
  },
  {
    id: 'of126',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(12),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[31].id,
  },
  {
    id: 'of127',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[31].id,
  },
  {
    id: 'of128',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[31].id,
  },
  {
    id: 'of129',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(63),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[32].id,
  },
  {
    id: 'of130',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[32].id,
  },
  {
    id: 'of131',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[32].id,
  },
  {
    id: 'of132',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[32].id,
  },
  {
    id: 'of133',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(5),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[33].id,
  },
  {
    id: 'of134',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[33].id,
  },
  {
    id: 'of135',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(2),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[33].id,
  },
  {
    id: 'of136',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[33].id,
  },
  {
    id: 'of137',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(15),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[34].id,
  },
  {
    id: 'of138',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[34].id,
  },
  {
    id: 'of139',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[34].id,
  },
  {
    id: 'of140',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[34].id,
  },
  {
    id: 'of141',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(5),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[35].id,
  },
  {
    id: 'of142',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[35].id,
  },
  {
    id: 'of143',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[35].id,
  },
  {
    id: 'of144',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(28),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[35].id,
  },
  {
    id: 'of145',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(80),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[36].id,
  },
  {
    id: 'of146',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[36].id,
  },
  {
    id: 'of147',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[36].id,
  },
  {
    id: 'of148',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[36].id,
  },
  {
    id: 'of149',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(5),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[37].id,
  },
  {
    id: 'of150',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(30),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[37].id,
  },
  {
    id: 'of151',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[37].id,
  },
  {
    id: 'of152',
    creationDate: new Date(),
    decisionDate: null,
    plannedCalendarWeek: null,
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[37].id,
  },
  {
    id: 'of153',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(6),
    status: OfferStatesEnum.ACCEPTED,
    serviceProcessId: ServiceProcessesSeed[38].id,
  },
  {
    id: 'of154',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(6),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[38].id,
  },
  {
    id: 'of155',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(7),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[38].id,
  },
  {
    id: 'of156',
    creationDate: new Date(),
    decisionDate: new Date(),
    plannedCalendarWeek: null,
    price: new Decimal(8),
    status: OfferStatesEnum.REFUSED,
    serviceProcessId: ServiceProcessesSeed[38].id,
  },
];
