import { Prisma } from '@prisma/client'; 
 export const orderLinesSeed = [
  {
    id: 'ol001',
    netPrice: new Prisma.Decimal(30),
    orderId: 'o001',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(2),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(60)
  },
  {
    id: 'ol002',
    netPrice: new Prisma.Decimal(30),
    orderId: 'o002',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(7),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(210)
  },
  {
    id: 'ol003',
    netPrice: new Prisma.Decimal(10),
    orderId: 'o003',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(100)
  },
  {
    id: 'ol004',
    netPrice: new Prisma.Decimal(20),
    orderId: 'o004',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(200)
  },
  {
    id: 'ol005',
    netPrice: new Prisma.Decimal(20),
    orderId: 'o005',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(9),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(180)
  },
  {
    id: 'ol006',
    netPrice: new Prisma.Decimal(60),
    orderId: 'o006',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(600)
  },
  {
    id: 'ol007',
    netPrice: new Prisma.Decimal(20),
    orderId: 'o007',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(5),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(100)
  },
  {
    id: 'ol008',
    netPrice: new Prisma.Decimal(50),
    orderId: 'o008',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(4),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(200)
  },
  {
    id: 'ol009',
    netPrice: new Prisma.Decimal(50),
    orderId: 'o009',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(6),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(300)
  },
  {
    id: 'ol010',
    netPrice: new Prisma.Decimal(40),
    orderId: 'o010',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(7),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(280)
  },
  {
    id: 'ol011',
    netPrice: new Prisma.Decimal(20),
    orderId: 'o011',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(6),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(120)
  },
  {
    id: 'ol012',
    netPrice: new Prisma.Decimal(30),
    orderId: 'o012',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(1),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(30)
  },
  {
    id: 'ol013',
    netPrice: new Prisma.Decimal(30),
    orderId: 'o013',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(1),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(30)
  },
  {
    id: 'ol014',
    netPrice: new Prisma.Decimal(80),
    orderId: 'o014',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(5),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(400)
  },
  {
    id: 'ol015',
    netPrice: new Prisma.Decimal(60),
    orderId: 'o015',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(9),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(540)
  },
  {
    id: 'ol016',
    netPrice: new Prisma.Decimal(40),
    orderId: 'o016',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(400)
  },
  {
    id: 'ol017',
    netPrice: new Prisma.Decimal(60),
    orderId: 'o017',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(6),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(360)
  },
  {
    id: 'ol018',
    netPrice: new Prisma.Decimal(30),
    orderId: 'o018',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(3),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(90)
  },
  {
    id: 'ol019',
    netPrice: new Prisma.Decimal(70),
    orderId: 'o019',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(4),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(280)
  },
  {
    id: 'ol020',
    netPrice: new Prisma.Decimal(80),
    orderId: 'o020',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(6),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(480)
  },
  {
    id: 'ol021',
    netPrice: new Prisma.Decimal(30),
    orderId: 'o021',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(8),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(240)
  },
  {
    id: 'ol022',
    netPrice: new Prisma.Decimal(40),
    orderId: 'o022',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(1),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(40)
  },
  {
    id: 'ol023',
    netPrice: new Prisma.Decimal(50),
    orderId: 'o023',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(500)
  },
  {
    id: 'ol024',
    netPrice: new Prisma.Decimal(60),
    orderId: 'o024',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(6),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(360)
  },
  {
    id: 'ol025',
    netPrice: new Prisma.Decimal(30),
    orderId: 'o025',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(3),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(90)
  },
  {
    id: 'ol026',
    netPrice: new Prisma.Decimal(60),
    orderId: 'o026',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(600)
  },
  {
    id: 'ol027',
    netPrice: new Prisma.Decimal(10),
    orderId: 'o027',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(2),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(20)
  },
  {
    id: 'ol028',
    netPrice: new Prisma.Decimal(10),
    orderId: 'o028',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(7),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(70)
  },
  {
    id: 'ol029',
    netPrice: new Prisma.Decimal(20),
    orderId: 'o029',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(9),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(180)
  },
  {
    id: 'ol030',
    netPrice: new Prisma.Decimal(50),
    orderId: 'o030',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(8),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(400)
  },
  {
    id: 'ol031',
    netPrice: new Prisma.Decimal(20),
    orderId: 'o031',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(6),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(120)
  },
  {
    id: 'ol032',
    netPrice: new Prisma.Decimal(30),
    orderId: 'o032',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(4),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(120)
  },
  {
    id: 'ol033',
    netPrice: new Prisma.Decimal(50),
    orderId: 'o033',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(9),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(450)
  },
  {
    id: 'ol034',
    netPrice: new Prisma.Decimal(10),
    orderId: 'o034',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(6),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(60)
  },
  {
    id: 'ol035',
    netPrice: new Prisma.Decimal(50),
    orderId: 'o035',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(3),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(150)
  },
  {
    id: 'ol036',
    netPrice: new Prisma.Decimal(40),
    orderId: 'o036',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(7),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(280)
  },
  {
    id: 'ol037',
    netPrice: new Prisma.Decimal(60),
    orderId: 'o037',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(600)
  },
  {
    id: 'ol038',
    netPrice: new Prisma.Decimal(60),
    orderId: 'o038',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(5),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(300)
  },
  {
    id: 'ol039',
    netPrice: new Prisma.Decimal(30),
    orderId: 'o039',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(1),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(30)
  }
]