/*
 * Copyright Fraunhofer Institute for Material Flow and Logistics
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * For details on the licensing terms, see the LICENSE file.
 * SPDX-License-Identifier: Apache-2.0
 */

import { OrderLine, Prisma } from '@prisma/client';
import { ProductsSeed } from './products.seed';

export const OrderLinesSeed = <OrderLine[]>[
  {
    id: 'ol001',
    netPrice: new Prisma.Decimal(3),
    orderId: 'o001',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(2),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3),
  },
  {
    id: 'ol002',
    netPrice: new Prisma.Decimal(3),
    orderId: 'o002',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(7),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(21),
  },
  {
    id: 'ol003',
    netPrice: new Prisma.Decimal(1),
    orderId: 'o003',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(10),
  },
  {
    id: 'ol004',
    netPrice: new Prisma.Decimal(2),
    orderId: 'o004',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(20),
  },
  {
    id: 'ol005',
    netPrice: new Prisma.Decimal(2),
    orderId: 'o005',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(9),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(18),
  },
  {
    id: 'ol006',
    netPrice: new Prisma.Decimal(6),
    orderId: 'o006',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(60),
  },
  {
    id: 'ol007',
    netPrice: new Prisma.Decimal(2),
    orderId: 'o007',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(5),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(10),
  },
  {
    id: 'ol008',
    netPrice: new Prisma.Decimal(5),
    orderId: 'o008',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(4),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(20),
  },
  {
    id: 'ol009',
    netPrice: new Prisma.Decimal(5),
    orderId: 'o009',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(6),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(30),
  },
  {
    id: 'ol010',
    netPrice: new Prisma.Decimal(4),
    orderId: 'o010',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(7),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(28),
  },
  {
    id: 'ol011',
    netPrice: new Prisma.Decimal(2),
    orderId: 'o011',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(6),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(12),
  },
  {
    id: 'ol012',
    netPrice: new Prisma.Decimal(3),
    orderId: 'o012',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(1),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3),
  },
  {
    id: 'ol013',
    netPrice: new Prisma.Decimal(3),
    orderId: 'o013',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(1),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3),
  },
  {
    id: 'ol014',
    netPrice: new Prisma.Decimal(8),
    orderId: 'o014',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(5),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(40),
  },
  {
    id: 'ol015',
    netPrice: new Prisma.Decimal(6),
    orderId: 'o015',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(9),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(54),
  },
  {
    id: 'ol016',
    netPrice: new Prisma.Decimal(8),
    orderId: 'o016',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(80),
  },
  {
    id: 'ol017',
    netPrice: new Prisma.Decimal(6),
    orderId: 'o017',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(6),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(36),
  },
  {
    id: 'ol018',
    netPrice: new Prisma.Decimal(3),
    orderId: 'o018',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(3),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(9),
  },
  {
    id: 'ol019',
    netPrice: new Prisma.Decimal(7),
    orderId: 'o019',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(4),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(28),
  },
  {
    id: 'ol020',
    netPrice: new Prisma.Decimal(8),
    orderId: 'o020',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(6),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(48),
  },
  {
    id: 'ol021',
    netPrice: new Prisma.Decimal(3),
    orderId: 'o021',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(8),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(24),
  },
  {
    id: 'ol022',
    netPrice: new Prisma.Decimal(1),
    orderId: 'o022',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(1),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1),
  },
  {
    id: 'ol023',
    netPrice: new Prisma.Decimal(5),
    orderId: 'o023',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(50),
  },
  {
    id: 'ol024',
    netPrice: new Prisma.Decimal(6),
    orderId: 'o024',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(6),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(36),
  },
  {
    id: 'ol025',
    netPrice: new Prisma.Decimal(3),
    orderId: 'o025',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(3),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(9),
  },
  {
    id: 'ol026',
    netPrice: new Prisma.Decimal(6),
    orderId: 'o026',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(60),
  },
  {
    id: 'ol027',
    netPrice: new Prisma.Decimal(1),
    orderId: 'o027',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(2),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2),
  },
  {
    id: 'ol028',
    netPrice: new Prisma.Decimal(1),
    orderId: 'o028',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(7),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(7),
  },
  {
    id: 'ol029',
    netPrice: new Prisma.Decimal(2),
    orderId: 'o029',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(9),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(18),
  },
  {
    id: 'ol030',
    netPrice: new Prisma.Decimal(5),
    orderId: 'o030',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(8),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(40),
  },
  {
    id: 'ol031',
    netPrice: new Prisma.Decimal(2),
    orderId: 'o031',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(6),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(12),
  },
  {
    id: 'ol032',
    netPrice: new Prisma.Decimal(3),
    orderId: 'o032',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(4),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(12),
  },
  {
    id: 'ol033',
    netPrice: new Prisma.Decimal(7),
    orderId: 'o033',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(9),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(63),
  },
  {
    id: 'ol034',
    netPrice: new Prisma.Decimal(1),
    orderId: 'o034',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(6),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(60),
  },
  {
    id: 'ol035',
    netPrice: new Prisma.Decimal(5),
    orderId: 'o035',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(3),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(45),
  },
  {
    id: 'ol036',
    netPrice: new Prisma.Decimal(4),
    orderId: 'o036',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(7),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(28),
  },
  {
    id: 'ol037',
    netPrice: new Prisma.Decimal(8),
    orderId: 'o037',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(70),
  },
  {
    id: 'ol038',
    netPrice: new Prisma.Decimal(6),
    orderId: 'o038',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(5),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(90),
  },
  {
    id: 'ol039',
    netPrice: new Prisma.Decimal(3),
    orderId: 'o039',
    itemId: ProductsSeed[0].id,
    requestedQuantity: new Prisma.Decimal(1),
    partialDeliveryAllowed: false,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(6),
  },
];
