import { Prisma } from '@prisma/client'; 
 export const orderLinesSeed = [
  {
    id: 'ol001',
    netPrice: new Prisma.Decimal(1212),
    orderId: 'o001',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(12123.76)
  },
  {
    id: 'ol002',
    netPrice: new Prisma.Decimal(341),
    orderId: 'o002',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(7),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2388.1)
  },
  {
    id: 'ol003',
    netPrice: new Prisma.Decimal(302),
    orderId: 'o003',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(8),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2423.94)
  },
  {
    id: 'ol004',
    netPrice: new Prisma.Decimal(522),
    orderId: 'o004',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(5),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2610.59)
  },
  {
    id: 'ol005',
    netPrice: new Prisma.Decimal(93),
    orderId: 'o005',
    itemId: 'prod2',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1876.23)
  },
  {
    id: 'ol006',
    netPrice: new Prisma.Decimal(116),
    orderId: 'o006',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(60),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(6987.56)
  },
  {
    id: 'ol007',
    netPrice: new Prisma.Decimal(68),
    orderId: 'o007',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1365.79)
  },
  {
    id: 'ol008',
    netPrice: new Prisma.Decimal(45),
    orderId: 'o008',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(50),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2264.67)
  },
  {
    id: 'ol009',
    netPrice: new Prisma.Decimal(79),
    orderId: 'o009',
    itemId: 'prod3',
    requestedQuantity: new Prisma.Decimal(50),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3987.67)
  },
  {
    id: 'ol010',
    netPrice: new Prisma.Decimal(70),
    orderId: 'o010',
    itemId: 'prod3',
    requestedQuantity: new Prisma.Decimal(40),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2836.67)
  },
  {
    id: 'ol011',
    netPrice: new Prisma.Decimal(63),
    orderId: 'o011',
    itemId: 'prod3',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1278.23)
  },
  {
    id: 'ol012',
    netPrice: new Prisma.Decimal(132),
    orderId: 'o012',
    itemId: 'prod3',
    requestedQuantity: new Prisma.Decimal(30),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3987.12)
  },
  {
    id: 'ol013',
    netPrice: new Prisma.Decimal(129),
    orderId: 'o013',
    itemId: 'prod4',
    requestedQuantity: new Prisma.Decimal(30),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3897.78)
  },
  {
    id: 'ol014',
    netPrice: new Prisma.Decimal(170),
    orderId: 'o014',
    itemId: 'prod4',
    requestedQuantity: new Prisma.Decimal(80),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(13657.67)
  },
  {
    id: 'ol015',
    netPrice: new Prisma.Decimal(91),
    orderId: 'o015',
    itemId: 'prod4',
    requestedQuantity: new Prisma.Decimal(60),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(5489.67)
  },
  {
    id: 'ol016',
    netPrice: new Prisma.Decimal(106),
    orderId: 'o016',
    itemId: 'prod4',
    requestedQuantity: new Prisma.Decimal(40),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(4254.78)
  },
  {
    id: 'ol017',
    netPrice: new Prisma.Decimal(61),
    orderId: 'o017',
    itemId: 'prod4',
    requestedQuantity: new Prisma.Decimal(60),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3678.23)
  },
  {
    id: 'ol018',
    netPrice: new Prisma.Decimal(226),
    orderId: 'o018',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(30),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(6786.45)
  },
  {
    id: 'ol019',
    netPrice: new Prisma.Decimal(120),
    orderId: 'o019',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(70),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(8456.57)
  },
  {
    id: 'ol020',
    netPrice: new Prisma.Decimal(60),
    orderId: 'o020',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(80),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(4878.75)
  },
  {
    id: 'ol021',
    netPrice: new Prisma.Decimal(984),
    orderId: 'o021',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(8),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(7878.89)
  },
  {
    id: 'ol022',
    netPrice: new Prisma.Decimal(122),
    orderId: 'o022',
    itemId: 'prod2',
    requestedQuantity: new Prisma.Decimal(40),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(4896.45)
  },
  {
    id: 'ol023',
    netPrice: new Prisma.Decimal(117),
    orderId: 'o023',
    itemId: 'prod2',
    requestedQuantity: new Prisma.Decimal(50),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(5893.23)
  },
  {
    id: 'ol024',
    netPrice: new Prisma.Decimal(60),
    orderId: 'o024',
    itemId: 'prod2',
    requestedQuantity: new Prisma.Decimal(60),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3607.9)
  },
  {
    id: 'ol025',
    netPrice: new Prisma.Decimal(312),
    orderId: 'o025',
    itemId: 'prod3',
    requestedQuantity: new Prisma.Decimal(30),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(9360.67)
  },
  {
    id: 'ol026',
    netPrice: new Prisma.Decimal(115),
    orderId: 'o026',
    itemId: 'prod3',
    requestedQuantity: new Prisma.Decimal(60),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(6904.78)
  },
  {
    id: 'ol027',
    netPrice: new Prisma.Decimal(206),
    orderId: 'o027',
    itemId: 'prod3',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2065.24)
  },
  {
    id: 'ol028',
    netPrice: new Prisma.Decimal(795),
    orderId: 'o028',
    itemId: 'prod3',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(7956.34)
  },
  {
    id: 'ol029',
    netPrice: new Prisma.Decimal(54),
    orderId: 'o029',
    itemId: 'prod3',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1080.67)
  },
  {
    id: 'ol030',
    netPrice: new Prisma.Decimal(99),
    orderId: 'o030',
    itemId: 'prod4',
    requestedQuantity: new Prisma.Decimal(50),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(4957.36)
  },
  {
    id: 'ol031',
    netPrice: new Prisma.Decimal(364),
    orderId: 'o031',
    itemId: 'prod4',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(7289.34)
  },
  {
    id: 'ol032',
    netPrice: new Prisma.Decimal(42),
    orderId: 'o032',
    itemId: 'prod4',
    requestedQuantity: new Prisma.Decimal(30),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1267.56)
  },
  {
    id: 'ol033',
    netPrice: new Prisma.Decimal(90),
    orderId: 'o033',
    itemId: 'prod4',
    requestedQuantity: new Prisma.Decimal(50),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(4506.57)
  },
  {
    id: 'ol034',
    netPrice: new Prisma.Decimal(698),
    orderId: 'o034',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(6985.46)
  },
  {
    id: 'ol035',
    netPrice: new Prisma.Decimal(317),
    orderId: 'o035',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(50),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(15894.78)
  },
  {
    id: 'ol036',
    netPrice: new Prisma.Decimal(71),
    orderId: 'o036',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(40),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2847.57)
  },
  {
    id: 'ol037',
    netPrice: new Prisma.Decimal(166),
    orderId: 'o037',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(60),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(9986.56)
  },
  {
    id: 'ol038',
    netPrice: new Prisma.Decimal(159),
    orderId: 'o038',
    itemId: 'prod2',
    requestedQuantity: new Prisma.Decimal(60),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(9573.67)
  },
  {
    id: 'ol039',
    netPrice: new Prisma.Decimal(139),
    orderId: 'o039',
    itemId: 'prod2',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2794.68)
  },
  {
    id: 'ol040',
    netPrice: new Prisma.Decimal(78),
    orderId: 'o040',
    itemId: 'prod2',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1578.57)
  },
  {
    id: 'ol041',
    netPrice: new Prisma.Decimal(107),
    orderId: 'o041',
    itemId: 'prod2',
    requestedQuantity: new Prisma.Decimal(50),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(5364.67)
  },
  {
    id: 'ol042',
    netPrice: new Prisma.Decimal(114),
    orderId: 'o042',
    itemId: 'prod2',
    requestedQuantity: new Prisma.Decimal(60),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(6896.45)
  },
  {
    id: 'ol043',
    netPrice: new Prisma.Decimal(502),
    orderId: 'o043',
    itemId: 'prod3',
    requestedQuantity: new Prisma.Decimal(15),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(7535.67)
  },
  {
    id: 'ol044',
    netPrice: new Prisma.Decimal(210),
    orderId: 'o044',
    itemId: 'prod4',
    requestedQuantity: new Prisma.Decimal(25),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(5257.55)
  },
  {
    id: 'ol045',
    netPrice: new Prisma.Decimal(100),
    orderId: 'o045',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(35),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3534.78)
  },
  {
    id: 'ol046',
    netPrice: new Prisma.Decimal(58),
    orderId: 'o046',
    itemId: 'prod2',
    requestedQuantity: new Prisma.Decimal(40),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2357.46)
  },
  {
    id: 'ol047',
    netPrice: new Prisma.Decimal(50),
    orderId: 'o047',
    itemId: 'prod3',
    requestedQuantity: new Prisma.Decimal(50),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2503.75)
  },
  {
    id: 'ol048',
    netPrice: new Prisma.Decimal(114),
    orderId: 'o048',
    itemId: 'prod4',
    requestedQuantity: new Prisma.Decimal(60),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(6895.46)
  },
  {
    id: 'ol049',
    netPrice: new Prisma.Decimal(78),
    orderId: 'o049',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1576.79)
  },
  {
    id: 'ol050',
    netPrice: new Prisma.Decimal(126),
    orderId: 'o050',
    itemId: 'prod2',
    requestedQuantity: new Prisma.Decimal(30),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3784.67)
  },
  {
    id: 'ol051',
    netPrice: new Prisma.Decimal(52),
    orderId: 'o051',
    itemId: 'prod3',
    requestedQuantity: new Prisma.Decimal(40),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2089.56)
  },
  {
    id: 'ol052',
    netPrice: new Prisma.Decimal(117),
    orderId: 'o052',
    itemId: 'prod4',
    requestedQuantity: new Prisma.Decimal(50),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(5893.56)
  },
  {
    id: 'ol053',
    netPrice: new Prisma.Decimal(113),
    orderId: 'o053',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(60),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(6785.57)
  },
  {
    id: 'ol054',
    netPrice: new Prisma.Decimal(130),
    orderId: 'o054',
    itemId: 'prod2',
    requestedQuantity: new Prisma.Decimal(25),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3250.67)
  },
  {
    id: 'ol055',
    netPrice: new Prisma.Decimal(50),
    orderId: 'o055',
    itemId: 'prod3',
    requestedQuantity: new Prisma.Decimal(35),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1750.65)
  },
  {
    id: 'ol056',
    netPrice: new Prisma.Decimal(50),
    orderId: 'o056',
    itemId: 'prod4',
    requestedQuantity: new Prisma.Decimal(45),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2250.67)
  },
  {
    id: 'ol057',
    netPrice: new Prisma.Decimal(116),
    orderId: 'o057',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(30),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3506.78)
  },
  {
    id: 'ol058',
    netPrice: new Prisma.Decimal(71),
    orderId: 'o058',
    itemId: 'prod2',
    requestedQuantity: new Prisma.Decimal(50),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3556.35)
  },
  {
    id: 'ol059',
    netPrice: new Prisma.Decimal(129),
    orderId: 'o059',
    itemId: 'prod3',
    requestedQuantity: new Prisma.Decimal(60),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(7784.67)
  },
  {
    id: 'ol060',
    netPrice: new Prisma.Decimal(210),
    orderId: 'o060',
    itemId: 'prod4',
    requestedQuantity: new Prisma.Decimal(25),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(5250.78)
  },
  {
    id: 'ol061',
    netPrice: new Prisma.Decimal(192),
    orderId: 'o061',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(35),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(6750.78)
  },
  {
    id: 'ol062',
    netPrice: new Prisma.Decimal(94),
    orderId: 'o062',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(45),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(4250.12)
  },
  {
    id: 'ol063',
    netPrice: new Prisma.Decimal(171),
    orderId: 'o063',
    itemId: 'prod2',
    requestedQuantity: new Prisma.Decimal(50),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(8567.56)
  },
  {
    id: 'ol064',
    netPrice: new Prisma.Decimal(112),
    orderId: 'o064',
    itemId: 'prod2',
    requestedQuantity: new Prisma.Decimal(60),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(6756.64)
  },
  {
    id: 'ol065',
    netPrice: new Prisma.Decimal(233),
    orderId: 'o065',
    itemId: 'prod2',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(4674.73)
  },
  {
    id: 'ol066',
    netPrice: new Prisma.Decimal(457),
    orderId: 'o066',
    itemId: 'prod2',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(4578.78)
  },
  {
    id: 'ol067',
    netPrice: new Prisma.Decimal(229),
    orderId: 'o067',
    itemId: 'prod2',
    requestedQuantity: new Prisma.Decimal(30),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(6895.36)
  },
  {
    id: 'ol068',
    netPrice: new Prisma.Decimal(51),
    orderId: 'o068',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(50),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2589.85)
  },
  {
    id: 'ol069',
    netPrice: new Prisma.Decimal(164),
    orderId: 'o069',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(60),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(9895.76)
  },
  {
    id: 'ol070',
    netPrice: new Prisma.Decimal(210),
    orderId: 'o070',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(25),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(5255.89)
  },
  {
    id: 'ol071',
    netPrice: new Prisma.Decimal(193),
    orderId: 'o071',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(35),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(6759.32)
  },
  {
    id: 'ol072',
    netPrice: new Prisma.Decimal(56),
    orderId: 'o072',
    itemId: 'prod3',
    requestedQuantity: new Prisma.Decimal(40),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2257.45)
  },
  {
    id: 'ol073',
    netPrice: new Prisma.Decimal(51),
    orderId: 'o073',
    itemId: 'prod3',
    requestedQuantity: new Prisma.Decimal(50),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2578.65)
  },
  {
    id: 'ol074',
    netPrice: new Prisma.Decimal(86),
    orderId: 'o074',
    itemId: 'prod3',
    requestedQuantity: new Prisma.Decimal(60),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(6894.78)
  },
  {
    id: 'ol075',
    netPrice: new Prisma.Decimal(75),
    orderId: 'o075',
    itemId: 'prod3',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(4786.67)
  },
  {
    id: 'ol076',
    netPrice: new Prisma.Decimal(118),
    orderId: 'o076',
    itemId: 'prod3',
    requestedQuantity: new Prisma.Decimal(30),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3568.46)
  },
  {
    id: 'ol077',
    netPrice: new Prisma.Decimal(69),
    orderId: 'o077',
    itemId: 'prod4',
    requestedQuantity: new Prisma.Decimal(40),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2786.56)
  },
  {
    id: 'ol078',
    netPrice: new Prisma.Decimal(131),
    orderId: 'o078',
    itemId: 'prod4',
    requestedQuantity: new Prisma.Decimal(50),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(6578.56)
  },
  {
    id: 'ol079',
    netPrice: new Prisma.Decimal(61),
    orderId: 'o079',
    itemId: 'prod4',
    requestedQuantity: new Prisma.Decimal(50),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3069.23)
  },
  {
    id: 'ol080',
    netPrice: new Prisma.Decimal(170),
    orderId: 'o080',
    itemId: 'prod4',
    requestedQuantity: new Prisma.Decimal(25),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(4250.76)
  },
  {
    id: 'ol081',
    netPrice: new Prisma.Decimal(164),
    orderId: 'o081',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(35),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(5750.65)
  },
  {
    id: 'ol082',
    netPrice: new Prisma.Decimal(50),
    orderId: 'o082',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(45),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2250.78)
  },
  {
    id: 'ol083',
    netPrice: new Prisma.Decimal(151),
    orderId: 'o083',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(50),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(7578.56)
  },
  {
    id: 'ol084',
    netPrice: new Prisma.Decimal(114),
    orderId: 'o084',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(60),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(6893.56)
  },
  {
    id: 'ol085',
    netPrice: new Prisma.Decimal(103),
    orderId: 'o085',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2078.45)
  },
  {
    id: 'ol086',
    netPrice: new Prisma.Decimal(150),
    orderId: 'o086',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(30),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(4500.67)
  },
  {
    id: 'ol087',
    netPrice: new Prisma.Decimal(51),
    orderId: 'o087',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(40),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2078.35)
  },
  {
    id: 'ol088',
    netPrice: new Prisma.Decimal(151),
    orderId: 'o088',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(50),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(7589.56)
  },
  {
    id: 'ol089',
    netPrice: new Prisma.Decimal(64),
    orderId: 'o089',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(60),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3894.56)
  },
  {
    id: 'ol090',
    netPrice: new Prisma.Decimal(50),
    orderId: 'o090',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(25),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1250.67)
  },
  {
    id: 'ol091',
    netPrice: new Prisma.Decimal(193),
    orderId: 'o091',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(35),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(6750.78)
  },
  {
    id: 'ol092',
    netPrice: new Prisma.Decimal(50),
    orderId: 'o092',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(45),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2250.78)
  },
  {
    id: 'ol093',
    netPrice: new Prisma.Decimal(50),
    orderId: 'o093',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(50),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2508.56)
  },
  {
    id: 'ol094',
    netPrice: new Prisma.Decimal(129),
    orderId: 'o094',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(60),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(7785.67)
  },
  {
    id: 'ol095',
    netPrice: new Prisma.Decimal(194),
    orderId: 'o095',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3896.56)
  },
  {
    id: 'ol096',
    netPrice: new Prisma.Decimal(51),
    orderId: 'o096',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(30),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1556.43)
  },
  {
    id: 'ol097',
    netPrice: new Prisma.Decimal(69),
    orderId: 'o097',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(40),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2785.67)
  },
  {
    id: 'ol098',
    netPrice: new Prisma.Decimal(51),
    orderId: 'o098',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(50),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2589.21)
  },
  {
    id: 'ol099',
    netPrice: new Prisma.Decimal(63),
    orderId: 'o099',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(60),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3786.67)
  },
  {
    id: 'ol100',
    netPrice: new Prisma.Decimal(164),
    orderId: 'o100',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(60),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(9895.78)
  },
  {
    id: 'ol101',
    netPrice: new Prisma.Decimal(658),
    orderId: 'o101',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(6589.67)
  },
  {
    id: 'ol102',
    netPrice: new Prisma.Decimal(389),
    orderId: 'o102',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3894.67)
  },
  {
    id: 'ol103',
    netPrice: new Prisma.Decimal(378),
    orderId: 'o103',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3785.87)
  },
  {
    id: 'ol104',
    netPrice: new Prisma.Decimal(225),
    orderId: 'o104',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2250.98)
  },
  {
    id: 'ol105',
    netPrice: new Prisma.Decimal(298),
    orderId: 'o105',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(8),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2389.99)
  },
  {
    id: 'ol106',
    netPrice: new Prisma.Decimal(1067),
    orderId: 'o106',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(4),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(4268.65)
  },
  {
    id: 'ol107',
    netPrice: new Prisma.Decimal(4392),
    orderId: 'o107',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(2),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(8785.78)
  },
  {
    id: 'ol108',
    netPrice: new Prisma.Decimal(122),
    orderId: 'o108',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2456.87)
  },
  {
    id: 'ol109',
    netPrice: new Prisma.Decimal(812),
    orderId: 'o109',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(7),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(5685.78)
  },
  {
    id: 'ol110',
    netPrice: new Prisma.Decimal(1191),
    orderId: 'o110',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(5),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(5956.32)
  },
  {
    id: 'ol111',
    netPrice: new Prisma.Decimal(994),
    orderId: 'o111',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(4),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3976.78)
  },
  {
    id: 'ol112',
    netPrice: new Prisma.Decimal(926),
    orderId: 'o112',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(6),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(5556.89)
  },
  {
    id: 'ol113',
    netPrice: new Prisma.Decimal(405),
    orderId: 'o113',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(8),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3245.98)
  },
  {
    id: 'ol114',
    netPrice: new Prisma.Decimal(451),
    orderId: 'o114',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(3),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1353.78)
  },
  {
    id: 'ol115',
    netPrice: new Prisma.Decimal(429),
    orderId: 'o115',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(5),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2146.89)
  },
  {
    id: 'ol116',
    netPrice: new Prisma.Decimal(139),
    orderId: 'o116',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2785.78)
  },
  {
    id: 'ol117',
    netPrice: new Prisma.Decimal(182),
    orderId: 'o117',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1829.77)
  },
  {
    id: 'ol118',
    netPrice: new Prisma.Decimal(72),
    orderId: 'o118',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1455)
  },
  {
    id: 'ol119',
    netPrice: new Prisma.Decimal(105),
    orderId: 'o119',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(15),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1587.9)
  },
  {
    id: 'ol120',
    netPrice: new Prisma.Decimal(5833),
    orderId: 'o120',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(3),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(17500)
  },
  {
    id: 'ol121',
    netPrice: new Prisma.Decimal(459),
    orderId: 'o121',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(6),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2755.89)
  },
  {
    id: 'ol122',
    netPrice: new Prisma.Decimal(649),
    orderId: 'o122',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(6),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3896.89)
  },
  {
    id: 'ol123',
    netPrice: new Prisma.Decimal(85),
    orderId: 'o123',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(30),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2565.89)
  },
  {
    id: 'ol124',
    netPrice: new Prisma.Decimal(51),
    orderId: 'o124',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(70),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3578.54)
  },
  {
    id: 'ol125',
    netPrice: new Prisma.Decimal(556),
    orderId: 'o125',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(5),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2785.78)
  },
  {
    id: 'ol126',
    netPrice: new Prisma.Decimal(50),
    orderId: 'o126',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(65),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3258.66)
  },
  {
    id: 'ol127',
    netPrice: new Prisma.Decimal(51),
    orderId: 'o127',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(50),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2589.67)
  },
  {
    id: 'ol128',
    netPrice: new Prisma.Decimal(500),
    orderId: 'o128',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(35),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1750.78)
  },
  {
    id: 'ol129',
    netPrice: new Prisma.Decimal(500),
    orderId: 'o129',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(45),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2250.54)
  },
  {
    id: 'ol130',
    netPrice: new Prisma.Decimal(64),
    orderId: 'o130',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(60),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3895.67)
  },
  {
    id: 'ol131',
    netPrice: new Prisma.Decimal(50),
    orderId: 'o131',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(55),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2750.99)
  },
  {
    id: 'ol132',
    netPrice: new Prisma.Decimal(193),
    orderId: 'o132',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(35),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(6750.43)
  },
  {
    id: 'ol133',
    netPrice: new Prisma.Decimal(194),
    orderId: 'o133',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(40),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(7785.67)
  },
  {
    id: 'ol134',
    netPrice: new Prisma.Decimal(50),
    orderId: 'o134',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(75),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3750.76)
  },
  {
    id: 'ol135',
    netPrice: new Prisma.Decimal(562),
    orderId: 'o135',
    itemId: 'prod2',
    requestedQuantity: new Prisma.Decimal(4),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2250.88)
  },
  {
    id: 'ol136',
    netPrice: new Prisma.Decimal(458),
    orderId: 'o136',
    itemId: 'prod2',
    requestedQuantity: new Prisma.Decimal(6),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(2750.32)
  },
  {
    id: 'ol137',
    netPrice: new Prisma.Decimal(250),
    orderId: 'o137',
    itemId: 'prod2',
    requestedQuantity: new Prisma.Decimal(5),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1250.78)
  },
  {
    id: 'ol138',
    netPrice: new Prisma.Decimal(126),
    orderId: 'o138',
    itemId: 'prod2',
    requestedQuantity: new Prisma.Decimal(65),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(8250.64)
  },
  {
    id: 'ol139',
    netPrice: new Prisma.Decimal(193),
    orderId: 'o139',
    itemId: 'prod3',
    requestedQuantity: new Prisma.Decimal(35),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(6758.65)
  },
  {
    id: 'ol140',
    netPrice: new Prisma.Decimal(191),
    orderId: 'o140',
    itemId: 'prod3',
    requestedQuantity: new Prisma.Decimal(50),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(9584.87)
  },
  {
    id: 'ol141',
    netPrice: new Prisma.Decimal(76),
    orderId: 'o141',
    itemId: 'prod3',
    requestedQuantity: new Prisma.Decimal(60),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(4566.67)
  },
  {
    id: 'ol142',
    netPrice: new Prisma.Decimal(138),
    orderId: 'o142',
    itemId: 'prod3',
    requestedQuantity: new Prisma.Decimal(45),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(6250.76)
  },
  {
    id: 'ol143',
    netPrice: new Prisma.Decimal(122),
    orderId: 'o143',
    itemId: 'prod3',
    requestedQuantity: new Prisma.Decimal(55),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(6758.76)
  },
  {
    id: 'ol144',
    netPrice: new Prisma.Decimal(173),
    orderId: 'o144',
    itemId: 'prod3',
    requestedQuantity: new Prisma.Decimal(40),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(6945.9)
  },
  {
    id: 'ol145',
    netPrice: new Prisma.Decimal(50),
    orderId: 'o145',
    itemId: 'prod3',
    requestedQuantity: new Prisma.Decimal(65),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3256.99)
  },
  {
    id: 'ol146',
    netPrice: new Prisma.Decimal(164),
    orderId: 'o146',
    itemId: 'prod4',
    requestedQuantity: new Prisma.Decimal(35),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(5750.43)
  },
  {
    id: 'ol147',
    netPrice: new Prisma.Decimal(130),
    orderId: 'o147',
    itemId: 'prod4',
    requestedQuantity: new Prisma.Decimal(50),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(6535.76)
  },
  {
    id: 'ol148',
    netPrice: new Prisma.Decimal(51),
    orderId: 'o148',
    itemId: 'prod4',
    requestedQuantity: new Prisma.Decimal(70),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(3587.64)
  },
  {
    id: 'ol149',
    netPrice: new Prisma.Decimal(219),
    orderId: 'o149',
    itemId: 'prod4',
    requestedQuantity: new Prisma.Decimal(30),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(6587.53)
  },
  {
    id: 'ol150',
    netPrice: new Prisma.Decimal(98),
    orderId: 'o150',
    itemId: 'prod4',
    requestedQuantity: new Prisma.Decimal(80),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(7897.56)
  },
  {
    id: 'ol151',
    netPrice: new Prisma.Decimal(182),
    orderId: 'o151',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1824.66)
  },
  {
    id: 'ol152',
    netPrice: new Prisma.Decimal(174),
    orderId: 'o152',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1745.22)
  },
  {
    id: 'ol153',
    netPrice: new Prisma.Decimal(169),
    orderId: 'o153',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1691.88)
  },
  {
    id: 'ol154',
    netPrice: new Prisma.Decimal(187),
    orderId: 'o154',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1875.33)
  },
  {
    id: 'ol155',
    netPrice: new Prisma.Decimal(174),
    orderId: 'o155',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1743.77)
  },
  {
    id: 'ol156',
    netPrice: new Prisma.Decimal(182),
    orderId: 'o156',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1822.44)
  },
  {
    id: 'ol157',
    netPrice: new Prisma.Decimal(185),
    orderId: 'o157',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(30),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1850.22)
  },
  {
    id: 'ol158',
    netPrice: new Prisma.Decimal(178),
    orderId: 'o158',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1782.33)
  },
  {
    id: 'ol159',
    netPrice: new Prisma.Decimal(192),
    orderId: 'o159',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(30),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1923.77)
  },
  {
    id: 'ol160',
    netPrice: new Prisma.Decimal(174),
    orderId: 'o160',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1745.44)
  },
  {
    id: 'ol161',
    netPrice: new Prisma.Decimal(187),
    orderId: 'o161',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(40),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1877.55)
  },
  {
    id: 'ol162',
    netPrice: new Prisma.Decimal(182),
    orderId: 'o162',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(30),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1821.33)
  },
  {
    id: 'ol163',
    netPrice: new Prisma.Decimal(179),
    orderId: 'o163',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(30),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1794.88)
  },
  {
    id: 'ol164',
    netPrice: new Prisma.Decimal(193),
    orderId: 'o164',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1932.77)
  },
  {
    id: 'ol165',
    netPrice: new Prisma.Decimal(180),
    orderId: 'o165',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1800.22)
  },
  {
    id: 'ol166',
    netPrice: new Prisma.Decimal(175),
    orderId: 'o166',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1755.44)
  },
  {
    id: 'ol167',
    netPrice: new Prisma.Decimal(191),
    orderId: 'o167',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1910.88)
  },
  {
    id: 'ol168',
    netPrice: new Prisma.Decimal(177),
    orderId: 'o168',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1777.33)
  },
  {
    id: 'ol169',
    netPrice: new Prisma.Decimal(182),
    orderId: 'o169',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1823.44)
  },
  {
    id: 'ol170',
    netPrice: new Prisma.Decimal(179),
    orderId: 'o170',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(30),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1792.55)
  },
  {
    id: 'ol171',
    netPrice: new Prisma.Decimal(193),
    orderId: 'o171',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1933.33)
  },
  {
    id: 'ol172',
    netPrice: new Prisma.Decimal(178),
    orderId: 'o172',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1788.77)
  },
  {
    id: 'ol173',
    netPrice: new Prisma.Decimal(185),
    orderId: 'o173',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1850.11)
  },
  {
    id: 'ol174',
    netPrice: new Prisma.Decimal(180),
    orderId: 'o174',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1800.22)
  },
  {
    id: 'ol175',
    netPrice: new Prisma.Decimal(192),
    orderId: 'o175',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1922.33)
  },
  {
    id: 'ol176',
    netPrice: new Prisma.Decimal(178),
    orderId: 'o176',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1788.88)
  },
  {
    id: 'ol177',
    netPrice: new Prisma.Decimal(183),
    orderId: 'o177',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1833.55)
  },
  {
    id: 'ol178',
    netPrice: new Prisma.Decimal(179),
    orderId: 'o178',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(40),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1799.22)
  },
  {
    id: 'ol179',
    netPrice: new Prisma.Decimal(191),
    orderId: 'o179',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(40),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1911.33)
  },
  {
    id: 'ol180',
    netPrice: new Prisma.Decimal(177),
    orderId: 'o180',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(40),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1777.77)
  },
  {
    id: 'ol181',
    netPrice: new Prisma.Decimal(184),
    orderId: 'o181',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1844.33)
  },
  {
    id: 'ol182',
    netPrice: new Prisma.Decimal(180),
    orderId: 'o182',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1801.77)
  },
  {
    id: 'ol183',
    netPrice: new Prisma.Decimal(192),
    orderId: 'o183',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(30),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1923.22)
  },
  {
    id: 'ol184',
    netPrice: new Prisma.Decimal(178),
    orderId: 'o184',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(30),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1789.33)
  },
  {
    id: 'ol185',
    netPrice: new Prisma.Decimal(183),
    orderId: 'o185',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(30),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1831.44)
  },
  {
    id: 'ol186',
    netPrice: new Prisma.Decimal(179),
    orderId: 'o186',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(30),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1798.55)
  },
  {
    id: 'ol187',
    netPrice: new Prisma.Decimal(191),
    orderId: 'o187',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(40),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1915.77)
  },
  {
    id: 'ol188',
    netPrice: new Prisma.Decimal(177),
    orderId: 'o188',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(40),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1779.22)
  },
  {
    id: 'ol189',
    netPrice: new Prisma.Decimal(184),
    orderId: 'o189',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(40),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1845.33)
  },
  {
    id: 'ol190',
    netPrice: new Prisma.Decimal(180),
    orderId: 'o190',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1802.77)
  },
  {
    id: 'ol191',
    netPrice: new Prisma.Decimal(192),
    orderId: 'o191',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1928.33)
  },
  {
    id: 'ol192',
    netPrice: new Prisma.Decimal(178),
    orderId: 'o192',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(50),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1788.88)
  },
  {
    id: 'ol193',
    netPrice: new Prisma.Decimal(183),
    orderId: 'o193',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1839.33)
  },
  {
    id: 'ol194',
    netPrice: new Prisma.Decimal(180),
    orderId: 'o194',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(30),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1800.22)
  },
  {
    id: 'ol195',
    netPrice: new Prisma.Decimal(191),
    orderId: 'o195',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(40),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1912.44)
  },
  {
    id: 'ol196',
    netPrice: new Prisma.Decimal(178),
    orderId: 'o196',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1789.33)
  },
  {
    id: 'ol197',
    netPrice: new Prisma.Decimal(184),
    orderId: 'o197',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(50),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1844.88)
  },
  {
    id: 'ol198',
    netPrice: new Prisma.Decimal(180),
    orderId: 'o198',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(30),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1801.33)
  },
  {
    id: 'ol199',
    netPrice: new Prisma.Decimal(192),
    orderId: 'o199',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1922.77)
  },
  {
    id: 'ol200',
    netPrice: new Prisma.Decimal(178),
    orderId: 'o200',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1788.33)
  },
  {
    id: 'ol201',
    netPrice: new Prisma.Decimal(184),
    orderId: 'o201',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1842.44)
  },
  {
    id: 'ol202',
    netPrice: new Prisma.Decimal(180),
    orderId: 'o202',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(30),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1800.22)
  },
  {
    id: 'ol203',
    netPrice: new Prisma.Decimal(192),
    orderId: 'o203',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(40),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1920.88)
  },
  {
    id: 'ol204',
    netPrice: new Prisma.Decimal(178),
    orderId: 'o204',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(10),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1789.77)
  },
  {
    id: 'ol205',
    netPrice: new Prisma.Decimal(184),
    orderId: 'o205',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(20),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1846.22)
  },
  {
    id: 'ol206',
    netPrice: new Prisma.Decimal(180),
    orderId: 'o206',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(30),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1803.33)
  },
  {
    id: 'ol207',
    netPrice: new Prisma.Decimal(192),
    orderId: 'o207',
    itemId: 'prod1',
    requestedQuantity: new Prisma.Decimal(15),
    partialDeliveryAllowed: true,
    unitOfMeasureCodeRequested: 'Stück',
    unitOfMeasureCodeAgreed: 'Stück',
    lineTotalAmount: new Prisma.Decimal(1925.44)
  }
]