---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bff
  name: bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  strategy: {}
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - image: container-registry.gitlab.cc-asp.fraunhofer.de/skala/ap3/core/bff:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          name: bff
          envFrom:
            - configMapRef:
                name: shared-envs
---

